version: "20.10.8"

services:
    # Backend API
    smart-brain-api:
        container_name: backend
        # image: node:14
        build: ./
        command: npm start
        working_dir: /usr/src/smart-brain-api
        environment:
            POSTGRES_URL: postgres://sally:secret@postgres:5432/smart-brain-docker
            POSTGRES_USER: Sally
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
        links:
            - postgres
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/smart-brain/api
    # Postgres
    postgres:
        environment:
            POSTGRES_USER: sally
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
        build: ./postgres
        ports:
            - "5433:5432"
